### ISSUE TITLE
Support for Fish Shell

### ISSUE THREAD

**Issue by nitay** [scalaenv/scalaenv#26]
Hi @mazgi, scalaenv doesn't work with [fish](https://fishshell.com/). Can you add support for it?
rbenv has it, I think [this](https://github.com/rbenv/rbenv/commit/5bfec84432e63c46df4724918080abe488ba64b4) is one of the main commits they used?

**Comment by 3tty0n** [comment]
Fish shell is supported by #44 🎉 

![rofatrepag](https://user-images.githubusercontent.com/8289812/28690315-b27975ae-7353-11e7-912a-23746bcb3d78.gif)
