### ISSUE TITLE
0.0.10 unreleased on GitHub & missing from Homebrew, 2.12.1 unavailable in releases

### ISSUE THREAD

**Issue by Blaisorblade** [scalaenv/scalaenv#34]
Hi! Saw a link in a community, this looks cool.

But Homebrew is stuck on 0.0.9, and given their formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/scalaenv.rb), an update would be easiest with a GitHub release—0.0.10 lacks a tag.

And by now, I guess you'd need a new release for 2.12.1.
OK, yes, I can use the `--HEAD` option, it's just a cosmetic matter.

**Comment by mazgi** [comment]
Thanks for letting me know!
I've released [v0.0.10](https://github.com/mazgi/scalaenv/releases/tag/version%2F0.0.10) and [v0.0.11](https://github.com/mazgi/scalaenv/releases/tag/version%2F0.0.11).
