### ISSUE TITLE
Any plans to add Dotty?

### ISSUE THREAD

**Issue by kgdinesh** [scalaenv/scalaenv#40]

**Comment by 3tty0n** [comment]
dotty support :tada:
```sh
scalaenv install dotty-0.1.2-RC1
scalaenv global dotty-0.1.2-RC1-bin-SNAPSHOT
scalaenv rehash
dotr
```

**Comment by kgdinesh** [comment]
Wow that was fast!

**Comment by 3tty0n** [comment]
0.0.13 is not available on homebrew yet. Please execute `$ brew install --HEAD scalaenv` or ` $ brew upgrade --fetch-HEAD scalaenv`temporarily. @kgdinesh

**Comment by kgdinesh** [comment]
Thanks @3tty0n.

One more thing, does it make sense to have **dotty** & **scala** work side by side?

pointing **scalaenv** to **dotty** gets rid of **scala** command and vice-versa, which is quite annoying.

**Comment by 3tty0n** [comment]
@kgdinesh Sorry for my late reply. 

> One more thing, does it make sense to have dotty & scala work side by side?

I agree with your opinion. 
Bi-directional version pointing like pyenv is needed.

**Comment by 3tty0n** [comment]
go #42
