### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by vikjam** [scalaenv/scalaenv#53]
Hi, I'm having a bit of trouble getting scalaenv working. Any advice on troubleshooting? 

```{bash}
$ brew update && brew install scalaenv
$ echo 'export PATH="${HOME}/.scalaenv/bin:${PATH}"' >> ~/.bash_profile
$ echo 'eval "$(scalaenv init -)"' >> ~/.bash_profile
$ source ~/.bash_profile
$ scalaenv install -l
/usr/local/bin/scalaenv-install: line 40: scala-build: command not found
/usr/local/bin/scalaenv-install: line 77: parse_options: command not found
```

**Comment by 3tty0n** [comment]
Hi, thank you for your reporting.

I’m investigating this problem now, so please try to install scalaenv via GitHub temporarily.

**Comment by 3tty0n** [comment]
In installing via Homebrew, brew makes symlink scalaenv's bin files. 
These lines make symlink of `libexec/bin` but not make `plugins/bin/scala-install` (https://github.com/Homebrew/homebrew-core/blob/2394e7fef7919dd8c0b4ca66375a9048412ba812/Formula/scalaenv.rb#L15L17). I think this is the cause of problem.

**Comment by 3tty0n** [comment]
https://github.com/Homebrew/homebrew-core/pull/24787#issuecomment-372103149 was merged into homebrew-core, so this problem is fixed.
Thank you for reporting.
