### ISSUE TITLE
Can I install all-contributors bot?

### ISSUE THREAD

**Issue by mazgi** [scalaenv/scalaenv#71]
Hi @3tty0n 

Thank you as always for the maintenance continuously ✨ 

I think that it will be wonderful if we can use the [all-contributors bot](https://allcontributors.org/) in this repository.
What do you think?

Please see also this issue: https://github.com/sbtenv/sbtenv/issues/48

**Comment by 3tty0n** [comment]
Sounds good. Would you install and enable that bot in this repository, @mazgi ?

**Comment by mazgi** [comment]
Sure!
@all-contributors please add @mazgi for maintenance

**Comment by mazgi** [comment]
ok, I've done the test.

@all-contributors please add @3tty0n for maintenance

**Comment by mazgi** [comment]
@all-contributors please add @3tty0n for code

**Comment by mazgi** [comment]
@all-contoributors please add @mazgi for code

**Comment by mazgi** [comment]
@all-contributors please add @mazgi for code

**Comment by mazgi** [comment]
@all-contributors please add @mazgi for code

**Comment by mazgi** [comment]
ok, it was fixed.

**Comment by mazgi** [comment]
Done 🎉 

Added the contributors as follows:

- They contributed at least once. ▶️ `code`
- The member of the organization. ▶️ `maintenance `
    - https://github.com/orgs/scalaenv/people

And I've made you the owner of this organization, @3tty0n ❤️
